# Generated by Django 3.1.12 on 2025-12-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('InnovWEB', 'InnovWEB'), ('SensorShowDown', 'SensorShowDown'), ('IdeaArena', 'IdeaArena'), ('Error Erase', 'Error Erase')], max_length=100)),
                ('description', models.TextField()),
                ('rounds_info', models.TextField()),
                ('rules', models.TextField()),
                ('faculty_coordinator_name', models.CharField(max_length=100)),
                ('faculty_coordinator_designation', models.CharField(max_length=100)),
                ('faculty_coordinator_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('InnovWEB', 'InnovWEB'), ('SensorShowDown', 'SensorShowDown'), ('IdeaArena', 'IdeaArena'), ('Error Erase', 'Error Erase')], max_length=100)),
                ('team_code', models.CharField(max_length=20, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('team_lead_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('teammate1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('teammate2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCoordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_coordinators', to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['team_code'], name='events_part_team_co_07c623_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['event', 'registration_date'], name='events_part_event_e8f1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['team_name'], name='events_part_team_na_1f5b08_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='events_part_email_271d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='events_even_name_d5901c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoordinator',
            index=models.Index(fields=['event', 'name'], name='events_stud_event_i_c4f1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcoordinator',
            index=models.Index(fields=['roll_number'], name='events_stud_roll_nu_6c382f_idx'),
        ),
    ]
